from typing import Any, Protocol, runtime_checkable
from rich.text import Text
from textual.strip import Strip
from textual.geometry import Size

@runtime_checkable
class RichLogInterface(Protocol):
    """Interface for RichLog with line and timer access."""
    lines: list[Strip]
    virtual_size: Size
    auto_scroll: bool
    
    def write(self, renderable: Any, *args, **kwargs) -> None: ...
    def refresh_line(self, y: int) -> None: ...
    def scroll_end(self, animate: bool = True) -> None: ...
    def set_timer(self, delay: float, callback: Any, name: str | None = None) -> Any: ...

@runtime_checkable
class SpinnerManager(Protocol):
    """Protocol for spinner management."""
    def start_spinner(self, message: Text | str) -> None: ...
    def update_spinner(self, message: Text | str) -> None: ...
    def stop_spinner(self) -> None: ...
    def tick_spinner(self) -> None: ...
    def cleanup(self) -> None: ...

@runtime_checkable
class MessageRenderer(Protocol):
    """Protocol for rendering conversation messages."""
    def add_user_message(self, message: str) -> None: ...
    def add_assistant_message(self, message: str) -> None: ...
    def add_system_message(self, message: str) -> None: ...
    def add_error(self, message: str) -> None: ...
    def add_command_result(self, lines: list[str], is_error: bool = False) -> None: ...

@runtime_checkable
class ToolRenderer(Protocol):
    """Protocol for rendering tool interactions."""
    def add_tool_call(self, display: Text | str, *args: Any) -> None: ...
    def start_tool_execution(self) -> None: ...
    def stop_tool_execution(self, success: bool = True) -> None: ...
    def update_progress_text(self, message: str | Text) -> None: ...
    def add_tool_result(self, result: str) -> None: ...
    def add_nested_tool_call(self, display: Text | str, depth: int, parent: str) -> None: ...
    def complete_nested_tool_call(self, tool_name: str, depth: int, parent: str, success: bool) -> None: ...
    def cleanup(self) -> None: ...

@runtime_checkable
class ScrollController(Protocol):
    """Protocol for handling scrolling and input events."""
    auto_scroll: bool
    
    def on_key(self, event: Any) -> None: ...
    def on_mouse_scroll_down(self, event: Any) -> None: ...
    def on_mouse_scroll_up(self, event: Any) -> None: ...
    def on_mouse_down(self, event: Any) -> None: ...
    def on_mouse_move(self, event: Any) -> None: ...
    def on_mouse_up(self, event: Any) -> None: ...
    def scroll_to_end(self, animate: bool = True) -> None: ...
    def cleanup(self) -> None: ...
